### ISSUE TITLE
API Explorer drop-downs

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#102]
0 results are returned for the following.

Object | Collection
Object | Exhibit 
Object | Related parties - Obj collected in (coll id)

**Comment by Conal-Tuohy** [comment]
- http://www.nma.gov.au/about/our-collection/our-apis/collection-explorer?endpoint=object&keywords=*&field=collection&sort=&format=simple&size=5
- http://www.nma.gov.au/about/our-collection/our-apis/collection-explorer?endpoint=object&keywords=*&field=location&sort=&format=simple&size=5
- http://www.nma.gov.au/about/our-collection/our-apis/collection-explorer?endpoint=object&keywords=*&field=collection_id&sort=&format=simple&size=5

**Comment by Conal-Tuohy** [comment]
Exhibit is fixed in dev (the data model for exhibitions/galleries had been in flux but it is now settled).

**Comment by Conal-Tuohy** [comment]
Pretty sure I've fixed the other two now: https://github.com/NationalMuseumAustralia/Collection-API-ETL/commit/74471b6c84cac5bf3a0a43990f23fd4c828d0b2b

To test.

**Comment by Conal-Tuohy** [comment]
Pretty sure I've fixed the other two now: https://github.com/NationalMuseumAustralia/Collection-API-ETL/commit/74471b6c84cac5bf3a0a43990f23fd4c828d0b2b

To test.

**Comment by f27wood** [comment]
Passed on NMA Test

**Comment by f27wood** [comment]
Passed in prod.
