### ISSUE TITLE
Page that links to all objects

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#103]
Is it possible for you to develop a page using the API that links to every object. This is for our web developers who are having trouble indexing Collection Explorer as part of the main websites search.

So the page would simply link to each object on Collection Explorer, with the Title being the link. And would be dynamically created to capture new objects as they are published.

I am not sure where the best place to host it would be, can discuss if possible first and then decide.

**Comment by Conal-Tuohy** [comment]
We certainly could do that.

It would be helpful to get a little more detail on what index they are building, and how they are building it. 

It sounds like they are wanting to crawl an HTML page. It would be a pretty large page, if it were a single page. If it's acceptable to them, we could more easily and robustly build a linked list of HTML pages; each containing _x_ number of object links, and a link to the next page of links.

Also, I wonder about the actual need for another index; if they want to provide a search interface to the collection, they could just use the API itself.

**Comment by f27wood** [comment]
No longer needed, closing this.
