### ISSUE TITLE
Stats dashboard

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#108]

**Comment by f27wood** [comment]
Please remove months and days with no results, and add http status code labels

**Comment by f27wood** [comment]
Also add limit and start to track harvesters

**Comment by f27wood** [comment]
All good on NMA test, ready to deploy to prod.

**Comment by Conal-Tuohy** [comment]
Deployed to production. Ready for your signoff.

**Comment by f27wood** [comment]
Tested and done
