### ISSUE TITLE
ETL success/failure reporting

### ISSUE THREAD

**Issue by Conal-Tuohy** [NationalMuseumAustralia/Collection-API#112]
Copy solr load failures to ETL log dir. Also send email at end of ETL to api@nma.gov.au

**Comment by f27wood** [comment]
Plus, email notifications if the API goes down

**Comment by Conal-Tuohy** [comment]
Now sending email on ETL completion

**Comment by Conal-Tuohy** [comment]
Email notifications if the API goes down should be handled by Nagios.

**Comment by Conal-Tuohy** [comment]
following up nagios issue with @staplegun

**Comment by Conal-Tuohy** [comment]
Closing, as Solr deposit failures are now being saved, and email sent on ETL completion. 

Punting API monitoring to issue #124
