### ISSUE TITLE
Doco - retrieving objects by dates, parties and places

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#114]
To include how to limit these to production dates, places and parties.

**Comment by Conal-Tuohy** [comment]
This is currently not possible; we will need to change the Solr search schema first, to distinguish production parties from other parties, production places from other places, and production dates from other dates.

**Comment by Conal-Tuohy** [comment]
Doco should say that this _can_ be done, but it has to be done client-side; explain what the relevant fields are.

**Comment by Conal-Tuohy** [comment]
I have tried to cover this in https://github.com/NationalMuseumAustralia/Collection-API/wiki/Retrieving-objects-by-date,-place,-or-party

**Comment by Conal-Tuohy** [comment]
I have clarified what's involved in filtering, as you suggested.

**Comment by f27wood** [comment]
Yep all good, info is all there now.
