### ISSUE TITLE
Doco - media

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#117]
I think some further doco on the images/media would be good. For example, how to find teh preferred image, or thumbnail image, etc.

Related issue https://github.com/NationalMuseumAustralia/Collection-API/issues/11

**Comment by Conal-Tuohy** [comment]
@f27wood to provide some examples of making sense of the media images

**Comment by Conal-Tuohy** [comment]
Write up as a wiki page about the "media" data format

**Comment by staplegun** [comment]
There is a new 'Common search strategies' section that talks about searching for objects for media. This might be sufficient for this issue?

https://github.com/NationalMuseumAustralia/Collection-API/wiki/Searching-the-API#media

**Comment by f27wood** [comment]
Yes I think that is sufficient, thx.
