### ISSUE TITLE
List of objects with multiple images that do not have a page number

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#118]
Are you able to run a script to provide us with a list of objects with more than one image in Piction, where there is no page number,

As reg can then use that list, to update the data of those images to include a page number = 1 

To be complete under maintenance.

**Comment by Conal-Tuohy** [comment]
@f27wood to check to see if the list of objects can be specified as a list of hyperlinks; if so this will make the process of data entry more convenient.

**Comment by f27wood** [comment]
No there isn't a hyperlink that can be appended so just a list of IRNs of objects that:
- Have more than one Piction image associated with them
- None of the associated images have a page number=1

BTW in most cases, we only put a page number = 1 rather than numbering all of the images with a 2, 3, 4, etc. unless there is a specific order. We only need those objects where no page number exists.

**Comment by Conal-Tuohy** [comment]
Done, and I will send the list of IRNs separately. There are about 25k of them (which amounts to a little over a quarter of the total number of distinct objects with any Piction images)

I am thinking this is a one-off ad hoc request, so I haven't committed the code to do this, but if it turns out that it _is_ needed again, the stylesheet is here:

```xsl
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
	<xsl:output method="text"/>
	<xsl:template match="/">
		<objects-with-multiple-unranked-images>
			<xsl:for-each-group select="/add/doc" group-by="for $irn in field[@name='EMu IRN for Related Objects'] return tokenize($irn)">
				<xsl:sort select="current-grouping-key()"/>
				<xsl:if test="not(current-group()/field[@name='Page Number'] = '1')">
					<!-- none of the images in this object's group have a page number = 1 -->
					<object><xsl:value-of select="current-grouping-key()"/></object><xsl:text>&#xa;</xsl:text>
				</xsl:if>
			</xsl:for-each-group>
		</objects-with-multiple-unranked-images>
	</xsl:template>
</xsl:stylesheet>
```

**Comment by f27wood** [comment]
Great! That was quick. And yes a one off request, although we may wish to check again sometime in the future so good to keep this code.

**Comment by f27wood** [comment]
I have checked the list you emailed me, and checked a few IRNs/objects and they do not have more than one Piction image, or are not yet published to CE and the API. I also checked these in Piction to make sure there is only one image associated to them.

Examples - not yet published online, and only have one Piction image in Piction

http://collectionsearch.nma.gov.au/object/10000
http://collectionsearch.nma.gov.au/object/10029

Examples - published online but only have one Piction image
http://collectionsearch.nma.gov.au/object/10310
http://collectionsearch.nma.gov.au/object/10427

When there is only one image associated to an object, there is no page number entered into Piction. Perhaps the script isn't filtering out objects with only one image?

**Comment by Conal-Tuohy** [comment]
Och you are dead right, of course. Let me fix that now.

**Comment by f27wood** [comment]
Revised list received AOK, and have tested some and they look like the right ones.

**Comment by Conal-Tuohy** [comment]
Posting an updated version of the stylesheet, which I actually now think _should_ be included in the build process, with the output file emailed to a responsible person at NMA. It might be worth thinking about a more general approach to flagging up "bad data", since we also have the issue of bogus EMu dates, and we also have some Piction images whose IRNs don't correspond to an actual IRN in EMu.
```xsl
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
	<xsl:output method="text"/>
	<xsl:template match="/">
		<objects-with-multiple-unranked-images>
			<xsl:for-each-group select="/add/doc" group-by="for $irn in field[@name='EMu IRN for Related Objects'] return tokenize($irn)">
				<xsl:sort select="current-grouping-key()"/>
				<!-- 
				Flag the group of images if it doesn't have either 
					a) exactly one member, or 
					b) a member with a Page Number = '1' 
				-->
				<xsl:if test="
					not(
						count(current-group()) = 1
						or
						current-group()/field[@name='Page Number'] = '1'
					)
				">
					<!-- none of the images in this object's group have a page number = 1 -->
					<object><xsl:value-of select="current-grouping-key()"/></object><xsl:text>&#xa;</xsl:text>
				</xsl:if>
			</xsl:for-each-group>
		</objects-with-multiple-unranked-images>
	</xsl:template>
</xsl:stylesheet>
```
