### ISSUE TITLE
Doco - data filtering

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#122]
A note to include in the doco how the data is filtered between the public and internal API. Maybe just for our own doco.

**Comment by f27wood** [comment]
Could just add some info to this document, and review for accuracy.

[API filters v3 - as implemented.docx](https://github.com/NationalMuseumAustralia/Collection-API/files/2655685/API.filters.v3.-.as.implemented.docx)

**Comment by Conal-Tuohy** [comment]
Compare the docx with the filter stylesheet.

**Comment by Conal-Tuohy** [comment]
Written up as https://github.com/NationalMuseumAustralia/Collection-API/wiki/ETL-filtering

**Comment by f27wood** [comment]
All good thx.
