### ISSUE TITLE
Registered users csv file

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#127]
It would be good at some stage to be able to download, or somehow have access to, the registered users information in a csv format, so we can open this up in excel. 
As we currently copy and paste from the email to an excel document.

**Comment by Conal-Tuohy** [comment]
There's also https://csapi-test.nma.gov.au/admin/consumers

**Comment by f27wood** [comment]
Ah that does the trick - if we can also add the organisation, use of the API and website. We would then have all of the info there, which meets our needs.

**Comment by Conal-Tuohy** [comment]
Oh unfortunately we don't (can't) record all that information in Kong (which is the source of that page); just the identifying data. Currently the only record we have of that other information is in the email.

**Comment by f27wood** [comment]
Ah okays, no probs. It isn't a big deal, more a nice to have. WIll close this.
