### ISSUE TITLE
Refactoring of the data ingestion pipeline 

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#148]
Logging this in GitHub as a way of tracking this.

In summary, this is to optimise the ETL pipeline so it does not take as long to process. Agreed to spend 15-20 hours on this.

**Comment by Conal-Tuohy** [comment]
I think you meant to write "... so that it does not consume as much memory during the process"? I'm honestly not sure what difference this will make to the total time elapsed (it may speed things up, but I'm not counting on it)
