### ISSUE TITLE
Rights statement when no associated image

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#27]
I've noticed that searching the Rights field, returns object records where there are no images associated with that object. This is because we are flagging the Creative Commons/Rights in the object record rather than the image, and some objects do not yet have an associated image, or the image has been restricted for the public API.

I am wondering if an object record does not have an associated image, whether it should be excluded from the rights search result. ? If possible and if a logical thing to do...?

**Comment by Conal-Tuohy** [comment]
I agree the API should not make any statements about rights in non-existent (or inaccessible) images. 

We could fairly easily filter out rights statements where there are no images, using the existing [TriX filtering step in the `sparql-to-solr.xpl` pipeline](https://github.com/Conal-Tuohy/NMA-API-ETL/blob/master/sparql-to-solr.xpl#L82-L88).

Incidentally, how is it that we have a rights statement at all in the case where there are no images at all? Are they just being assigned in a big sweep, whether there are images or not?

**Comment by f27wood** [comment]
To clarify - the rights statement doesn't show up in the object record, however the object is included in the search result.

And yes rights statements are being assigned to objects without images as we review by collection or an object type. The reason being that we are planning to eventually have images for all of the existing objects, so in the long term it is more efficient to review and mark up objects in logical groups. That way, once a photo of the object has been taken, the rights are already known.

**Comment by staplegun** [comment]
I decided this was easier to do during EMu ingest - then the rights statement won't appear anywhere.

**Comment by Conal-Tuohy** [comment]
Not sure about that, @staplegun, since an object may have no images listed in EMu but still have images in Piction, which should still be covered by licence specified in EMu. 

What do you say, @f27wood ? Should Piction images be covered by the licence stated in the EMu record?

**Comment by staplegun** [comment]
Well spotted. I have reverted the commit removing rights during the EMu ingest, and instead added it to the redact step.

**Comment by staplegun** [comment]
This is working successfully

- A Solr search for records with media but no rights returns 4 (which is bad, but proves the query pattern works):
http://54.252.247.143/solr/core_nma_public/select?fl=id&fq=media:*&fq=type:object&q=-rights:*
- Reversing the two parameters (has rights but no media) returns 0: http://54.252.247.143/solr/core_nma_public/select?fl=id&fq=rights:*&fq=type:object&q=-media:*

**Comment by staplegun** [comment]
To fix the four images with no rights - images should always have a right defined, so if there is no right then  the images should be redacted.

**Comment by f27wood** [comment]
I think this has been resolved as the rights statement is now with the image, noting that restricted images are displaying, when they should not. See https://github.com/NationalMuseumAustralia/Collection-API/issues/75

**Comment by staplegun** [comment]
Confirmed in production (both return 0 results)

https://data.nma.gov.au/solr/core_nma_internal/select?fl=id&fq=media:*&fq=type:object&q=-rights:*
https://data.nma.gov.au/solr/core_nma_internal/select?fl=id&fq=rights:*&fq=type:object&q=-media:*
