### ISSUE TITLE
Multiple versions of the same image and labelling of the images

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#3]
At the moment, object records with an associated image have a number of versions of the same image.

This will be addressed in the MVP, with each image having up to three versions only as follows. 

thumbnail image
A maximum width or height of 200 pixels

preview image
A maximum width or height of 640 or 800 pixels

web image
A maximum width or height of 1,600 pixels

The internal API will have one additional image version, with a maximum width or height of 2,000 pixels, to be labelled as 'full  image'. TBC.

**Comment by f27wood** [comment]
Also note that the MVP will only include EMU images only when no Piction image exists.

**Comment by staplegun** [comment]
Outstanding issues:

- Piction `original_4` and `original_5` are correctly being ignored, but `original_2` should not appear in the public API
- Piction `original_2` should have version `full image`
- All EMu images are being ignored (should only be if there is a Piction image instead)

**Comment by staplegun** [comment]
Also need to separate out the comma-delimited list of parent EMu objects. The initial attempt using `tokenize()` needs fixing.

**Comment by Conal-Tuohy** [comment]
did you want me to look at it? or is that just a note to self?

**Comment by staplegun** [comment]
`ERROR: file:/usr/local/NMA-API-ETL/piction-to-rdf.xsl:47:10:err:XPTY0004:A sequence of more than one item is not allowed as the first argument of fn:tokenize() ("31190", "31190") `

Fix. Changed from `<xsl:for-each select="tokenize( $related-objects, '[,\s?]+' )">`

To  `<xsl:for-each select="$related-objects!tokenize(., '[,\s?]+')">`

**Comment by staplegun** [comment]
Fixed in https://github.com/NationalMuseumAustralia/Collection-API-ETL/commit/e582e70aa4bb55a8871a6292ae1800310a90b736

**Comment by f27wood** [comment]
For doco, image versions for the public API are labelled:

thumbnail image
A maximum width or height of 200 pixels

preview image
A maximum width or height of 640 or 800 pixels

large image
A maximum width or height of 1,600 pixels

**Comment by f27wood** [comment]
Still need to test in internal API

**Comment by f27wood** [comment]
I'm not sure how to test that the additional  image is in the internal API. I thought Phar lap's heart would have an original_2 image, but I cannot see a "full image" when I go to:

http://nma-dev.conaltuohy.com/object/64620&apikey=2N19hAqFEXaHWGUpdHszUmDMXA2zQLEG

But not sure if this is because there is no original_2 image, or not.

Moving to blocked as I am not sure how to test this.

**Comment by staplegun** [comment]
Comparing Piction XML for media MA23064154 (for object 64620), against internal API output in https://data.nma.gov.au/media/MA23064154?apikey=XXX

* thumbnail -> thumbnail image
* web -> preview image
* original_2 -> full image
* original_3 -> large image
* original_4 -> missing (correct)
* original_5 -> missing (correct)
