### ISSUE TITLE
Add creditline field

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#49]
From EMu `RigCreditLine2` field.

**Comment by staplegun** [comment]
This is already available in `crm:P67i_is_referred_to_by` in CRM and `acknowledgement` in simple DC. The outstanding question is whether to include/exclude depending on the boolean in `RigAcknowledgement` (which currently is empty).

**Comment by f27wood** [comment]
This is one for Karen, but my understanding is that the credit line would be excluded if RigAcknowledgement equalled 'No". if empty or 'yes' then the creditline2 could be included.
Currently RigAcknowledgement isn;t populated as no creditLine2 data has been entered if not OK to publish.

**Comment by k1peterson** [comment]
Fiona is correct. The creditline2 data is excluded if RigAcknowledgement equals 'No'. Creditline2 data is included if RigAcknowledgement equals 'Yes' or is empty. RigAcknowledgement is not populated at present but we are about to start doing so soon. It is more often likely that there will be no creditline2 data when the RigAcknowledgement is 'No' but not always the case, hence the need to have the logic.

**Comment by staplegun** [comment]
The logic of using `RigAcknowledgement` has been added, but there are no records using it yet.

The `acknowledgement` field is currently not searchable - its content is not 'about' the resource so could skew searches, e.g. many say "Donated through the Australian Government".

**Comment by f27wood** [comment]
That makes sense not to make it searchable. I will ask Karen to create a test record so we can test this.

**Comment by staplegun** [comment]
Actually, it can be searchable as `acknowledgement=*`, we just won't add it to the record-wide `text=*` field. I think that was the intention but got lost amongst all the mapping working.

**Comment by f27wood** [comment]
Ah okays yes I can see now that acknowledgement is a searchable field. And agreed that it doesn't need to be in the text wide search.

**Comment by staplegun** [comment]
To clarify, `acknowledgement ` is a searchable field, except currently it isn't being populated - so that's an outstanding issue.

**Comment by staplegun** [comment]
Outstanding issue that the `acknowledgement` field has not been made searchable.

However there also are no records in the EMu XML file (19 July) containing the field `RigAcknowledgement`.

**Comment by staplegun** [comment]
Added `acknowledgement` field in Solr.

**Comment by staplegun** [comment]
Added followup issue for the `RigAcknowledgement` boolean in #86.
