### ISSUE TITLE
Add more narrative details

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#50]
EMu fields: `DesPurpose`, `DetNarrativeIdentifier`, `DesType`, `DesIntendedAudience`, `banner` (some are already in JSON-LD, just need adding to Simple DC format).

**Comment by f27wood** [comment]
These fields do not need to be in the public API, but do need to be in the internal API.

The DesIntendedAudience is used to filter the narratives - only those with the value of "Collection Explorer publish" are to be included in the Public API.

All of them are to be included in the internal API.

**Comment by f27wood** [comment]
Hmma actually DetNarrativeIdentifier needs to be in the public API as this groups the narratives.

Re banner images - we need to exclude these from the public API (unfortunately)  as not all have copyright to use externally.

**Comment by staplegun** [comment]
Removing this from release v1.0 - these are future fields that will be added for the internal API. Removal of Banner image is in issue #51.

**Comment by staplegun** [comment]
`DesIntendedAudience` is now in #73

**Comment by f27wood** [comment]
Closing this as I am not convinced that we need these extra fields. Will reopen if there is a use case for it.
