### ISSUE TITLE
Remove banner images from narratives

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#51]
Banner images have not been rights cleared so will need to be removed from the public API. Example: narrative 1737 "Aboriginal and Torres Strait Islander Affairs Art collection"

**Comment by f27wood** [comment]
The banner images are still displaying in the linked art format. See:

https://csapi-test.nma.gov.au/apiexplorer.html?endpoint=narrative&keywords=*Aboriginal+and+Torres+Strait+Islander+Affairs+Art+collection&field=text&sort=&format=json-ld&size=5

**Comment by staplegun** [comment]
Banner images have been removed from the public API but remain in the internal API.
