### ISSUE TITLE
Handle file names for EMu and Piction export data

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#53]
Piction exports are in a single file, EMu exports are in multiple files (one for each module type). The ETL ingest step takes the entity type as an input parameter.

Currently the file names to not always match the contained entity type. So the ETL should either map from the file name to the appropriate entity type, or automatically determine the entity type (e.g. by scanning a few records). It can then call the ingest step with the appropriate entity type parameter.

**Comment by Conal-Tuohy** [comment]
Addressed in https://github.com/Conal-Tuohy/NMA-API-ETL/commit/3922a3fda7428b43dfb25c6104f40df9610aeccf and https://github.com/Conal-Tuohy/NMA-API-ETL/commit/b0de4ff70947b5192e4633624fa688b0c60c29c1

The data files are currently still loaded by searching for files with a particular name, but the file type is determined by actually looking at the content of the file.

**Comment by staplegun** [comment]
Agreed process:
1. EMu and Piction extraction runs daily (Mon-Fri) at 7:00-8:00pm, output to 
 - `/mnt/emudata/full/<coded-filename>.xml`
 - `/mnt/damsdata/piction_solr_prod1.xml`
2. API ETL will run daily (Mon-Fri) at 9:00pm
3. Afterwards an archive of all files involved are placed in a job directory `/mnt/emudata/etl/<job-name>/`
 - EMu files are _moved_
 - Piction files are _copied_
 - log files are _copied_
4. Archived data files over 2 weeks old are deleted, archived log files over 6 months old are deleted.

**Comment by SimmoK** [comment]
Sounds good to me though you have the Piction filename wrong, it's just solr_prod1.xml.

**Comment by SimmoK** [comment]
Wait a min I'm confirming that those paths are correct, i see some conflicting doco on whether it's damsdata or dams_data. I'll confirm with Rick when he gets in soon.

**Comment by staplegun** [comment]
OK, thanks, I'll change the ETL scripts. And you are right about the piction file name, apologies. I've corrected the above comment.

**Comment by f27wood** [comment]
I cannot test this so moving it to done, based on your testing and knowledge of the issue.
