### ISSUE TITLE
Image rights statement in linked art version

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#57]
I just noticed that in the simple format, the image rights are mapped under HasVersion / Rights. This makes sense to me as the rights relate to the image. 

However,in the linked art format it looks like the rights relate to the object, as they are stated in "Subject_to". I would expect them to be under Representation / Rights so it is obvious they relate to the image.

Although i cannot test this in the dev API at the moment, so it may already have been changed.

Example:
Fourth object down:
http://nma.conaltuohy.com/apiexplorer.html?keywords=*convict+love+token&endpoint=object&field=text&sort=&format=json-ld&size=100

**Comment by staplegun** [comment]
This may be difficult without post-processing the record during JSON-LD construction. An alternative might be to make it clear that the rights statement refers to the media rather than the object or metadata.

**Comment by staplegun** [comment]
Decided option (2) is best - pulls correct data together in JSON-LD, can still present flatter structure in simple DC.

**Comment by Conal-Tuohy** [comment]
- [ ] Every `PhysicalObject` will have a `P138i _has_representation` property, which is an instance of `E36_Visual_Item`, and which bears the legal rights. 
- [ ] In turn, actual images, either from EMu or Piction, will hang off that `E36_Visual_Item` as values of its own `P138i _has_representation` property. 
- [ ] The  `PhysicalObject`'s `P138i _has_representation` property should be redacted if the property value has no  `P138i _has_representation` property value itself.
- [ ] The top-level `E36_Visual_Item` should have only one  `P138i _has_representation` property value; if there are two, then the EMu-sourced one should be redacted.

**Comment by staplegun** [comment]
Slight change in approach - instead of wrapping in a 'super image' entity, keep each image as a representation of the object, but add a parallel bundling of the images that is subject to the rights.

**Comment by f27wood** [comment]
I have tested this and all AOK, moved to done.
