### ISSUE TITLE
API Explorer fixes

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#58]
Changes to the API have broken parts of the API explorer

- JSON `data` wrapper element means the title/type isn't where it used to be
- resource displays show `null results`
- update the field drop-down list to the new schema in Solr
- geo map broken

Enhancement

- Move type drop-down to first (so is is clearer that the keywords box relates to the field specifiers (not the object type)

**Comment by f27wood** [comment]
I am not familiar with this issue so moving to done based on your testing.
