### ISSUE TITLE
Search doesn't tell you how many records its returning

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#6]
Search doesn't tell you how many records its returning which makes pagination difficult - this wouldn't be an issue if we do infinite scroll or something similar but if you want people to make their way through a result set its problematic.

**Comment by f27wood** [comment]
I believe this is a known issue which will be addressed in the public full version?

**Comment by f27wood** [comment]
Great!

I believe this would this meet Trove's need  below. Is that right?

•	Harvesting: Our harvester needs some way of determining how many records are in your API feed – so it can paginate through 100 records at a time and know when it’s reached the end. An example of this from another API feed can be seen here – they’ve given us the total record count in the field titled ‘found’:
https://www.awm.gov.au/direct/data.php?q=type:Art&count=50
Are you able to include a total record count in your API that we can use to do this?

**Comment by Conal-Tuohy** [comment]
Yes I think so! Could you maybe direct the Trove person to this issue, so they can comment directly?

**Comment by melGH** [comment]
Hi Conal & Fiona
Have checked with Julia & looks like the http response-header solution won't work for Trove. We need the result count or total record count to be within the json response - something like this example from NGV: http://www.ngv.vic.gov.au/custom/espa/collection/works

"took":2,"timed_out":false,"hits":{"total":69815,"hits":[{"_index":"collection_v2","_type":"works","_id":"98522","_score":1,"_source":{"artwork_id":"98522","title":"Dress and belt",
