### ISSUE TITLE
Empty production dates

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#60]
646 production dates have a note but no date data, which are failing to load into Solr as date-type fields rejects empty data. The conversion to Solr needs to ignore empty date data fields.

```
  <ProductionDates>
   <ProductionDate>
    <ProDateNotes_tab>Not provided</ProDateNotes_tab>
   </ProductionDate>
  </ProductionDates>
```

**Comment by Conal-Tuohy** [comment]
These data should probably be typed in the SPARQL layer too (and checked at that stage)

**Comment by staplegun** [comment]
Found a related use case, where there is only an earliest encoded date, but no default `AssDate0`:
```
<AssociatedDates>
   <AssociatedDates>
    <AssLatestDate0>1953</AssLatestDate0>
    <AssDateType_tab>Period of use</AssDateType_tab>
   </AssociatedDates>
</AssociatedDates>
```

**Comment by staplegun** [comment]
Don't want to use `AssDate0` as is often duplicates the earliest date, which is not accurate way of describing the whole date for this thing.
```
date: "11 Jul 2001 - 16 Aug 2017"
earliestDate: "2001-07-11"
latestDate: "2017-08-16"
```
ignoring `AssDate0`, just use earliest/latest
if no earliest/latest, copy `AssDate0` into them

If just one of earliest/latest, just use that
```
date: "- 16 Aug 2017"
latestDate: "2017-08-16"
```

**Comment by nmamanager** [comment]
This approach is confirmed.

With one question - if the xml includes the date type, it would also be good to include this, as this explains the date. For example: Period of use.

**Comment by nmamanager** [comment]
And some sample records for when it comes to testing:

Date range example: 227892
Latest date only: 116731
Earliest date only: 70136
Exact dates (i.e. no date range): 64620
