### ISSUE TITLE
Inward loan flag

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#72]
Add `InwardLoan` to internal API.

**Comment by staplegun** [comment]
This is searchable in the internal API in the `source` field, which contains `Inward loan`. Currently there is only one record: object 228418.

**Comment by f27wood** [comment]
How can I test this?
I tried 
http://nma-dev.conaltuohy.com/object/228418&apikey=2N19hAqFEXaHWGUpdHszUmDMXA2zQLEG
but no result..

**Comment by f27wood** [comment]
Moving this to blocked as I do not know how to test this

**Comment by staplegun** [comment]
Your link should work now, but there is a problem with that record - I have raised a new issue #76

**Comment by f27wood** [comment]
Re-tested, and not working, using this:

http://nma-dev.conaltuohy.com/object/228418&apikey=2N19hAqFEXaHWGUpdHszUmDMXA2zQLEG

**Comment by f27wood** [comment]
Tested in prod and working AOK.

https://data.nma.gov.au/object?limit=5&text=*two%20dowel%20rods&apikey=XXX&format=simple

**Comment by f27wood** [comment]
Hmm actually it doesn;t seem to have all the data in the record reopening this issue

**Comment by staplegun** [comment]
Closing as missing data is covered separately in issue #84.
