### ISSUE TITLE
Add narrative audience type field

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#73]
EMu field `DesIntendedAudience` is already in JSON-LD as a `crm:P2_has_type` and needs to be added to simple DC.

**Comment by staplegun** [comment]
Confirmed that although this is an audience field, really they are more statuses, eg. `Collection Explorer draft` or `Collection Explorer publish`, and in the future may include `API only`.

So using a CRM type is appropriate, and shouldn't be placed in `dc:audience`

**Comment by staplegun** [comment]
The `DesIntendedAudience` field appears in `crm:P2_has_type` in JSON-LD and `additionalType` in simple format.

Narrative records are excluded from the public API if the `DesIntendedAudience` field does NOT contain `Collection Explorer publish`.  If they are in the public API, the P2 and additionalType will contain `Collection Explorer publish`.

**Comment by f27wood** [comment]
Moving to blocked as unsure how to test. Tried to test using:

http://nma-dev.conaltuohy.com/narrative?limit=5&text=*defining%20moments&format=simple&apikey=2N19hAqFEXaHWGUpdHszUmDMXA2zQLEG

As a draft narrative in EMu is "Defining Moments in Australian History"

But not sure if I am testing it correctly.
