### ISSUE TITLE
Restricted images 

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#75]
It looks like the restricted images are not being restricted in the public API. Examples:

74079
35504

**Comment by Conal-Tuohy** [comment]
by "74079" and 35504 I assume you mean the images belonging to those objects i.e. http://nma-dev.conaltuohy.com/object/74049# and http://nma-dev.conaltuohy.com/object/35504# ?

**Comment by f27wood** [comment]
Yes, although a typo in your link, first one is

http://nma-dev.conaltuohy.com/object/74079#

Noting that the rights statement is "All rights reserved" rather than restricted. And searching for "all rights reserved" returns a lot of object records with images that should not be included.

**Comment by Conal-Tuohy** [comment]
The `filter.xsl` stylesheet filters out all EMu images from an object record if the rights are restricted, but this doesn't apply to the images imported from Piction. So the RDF dataset will actually include restricted images from Piction. We will need to filter those out at the second stage, where the RDF data is copied to Solr; we will need to redact those Piction images at that point.

**Comment by Conal-Tuohy** [comment]
Yes it would have slowed things down a little, for sure.

**Comment by Conal-Tuohy** [comment]
Done in https://github.com/NationalMuseumAustralia/Collection-API-ETL/commit/c7073b12aa4f4b2621b751753ba7b1f8e11e88e7 -- to test

**Comment by staplegun** [comment]
Fixed typo in https://github.com/NationalMuseumAustralia/Collection-API-ETL/commit/a9b35dbe8654cb1fb1e57e0c807dcc32ed99a2aa

**Comment by staplegun** [comment]
Is now fixed. Only available for testing on an interim server:

- Image now removed: http://13.210.207.100/apiexplorer.html?id=object/74079
- Image now removed: http://13.210.207.100/apiexplorer.html?id=object/35504
- A search on `reserved` (from All Rights Reserved) returns 0 http://13.210.207.100/apiexplorer.html?endpoint=object&keywords=reserved&field=rights&sort=&format=simple&size=5
- Whereas a search on `cc`: http://13.210.207.100/apiexplorer.html?endpoint=object&keywords=cc&field=rights&sort=&format=simple&size=5

**Comment by f27wood** [comment]
Tested and all AOK on nma-dev.conaltouhy.com
