### ISSUE TITLE
Internal API to include additional locations

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#77]
It does not look like the additional locations have been included in the internal API records.

From doco (API Filters):

For public API
If LocLevel1=Acton, then also include:
LocLevel2 (Gallery name to be converted to full name as outlined in API extra data doc)

For internal API, include the above plus all other location levels, being:
LocLevel3
LocLevel4
LocLevel5
LocLevel6
LocLevel7
LocLevel8

**Comment by f27wood** [comment]
Note that public API is to use DisplayGallery instead of LocLevel1 and LocLevel2. See https://github.com/NationalMuseumAustralia/Collection-API/issues/79

I think the internal APi should have the DisplayGallery plus all of the locations including level 1 and 2, so we can search just for "Acton" to find all objects on display. And we may wish to add other level1 locations down the track to the internal api only.

**Comment by staplegun** [comment]
5 object records have `LocLevel6` - all are Acton, there are none with `LocLevel7` or `LocLevel8`
55298
55299
55300
55313
55334

**Comment by f27wood** [comment]
What do you mean by "all are Acton"?  As only level 1 should be Acton...

Location levels for example records should be as as follows.

16529
Acton - Open coll. - Row 01 - Case 03 - Cab 01 - Shelf 04

55313
Acton - Open coll. - Row 01 - Case 02 - Cab 01 - Shelf 02

64549
Acton - GFA - Upper GFA - Communities - Lockhart River - Mission

**Comment by Conal-Tuohy** [comment]
I have a lot of questions about this:

- How are the locations actually modeled in EMu?
- What are the constraints on the data that can be entered?
- I assume the locations must be chosen from a list, and that there's a distinct list of possible locations for each "level"?
- Do the different values in the list (e.g. `Flemington`) also have identifiers which could be exposed in the exported XML?
- Is it the case that if you enter e.g. `Acton` at level 1, and `Landmarks` at level 2, does that give you a list in which `Flemington` would appear, whereas if you put something different at level 1 and 2 you would not get the option of `Flemington` in level 3? Or are their no co-occurrence constraints across the different levels (i.e. the selection lists for a given level are always the same regardless of what you've selected for other levels).

**Comment by f27wood** [comment]
> > How are the locations actually modeled in EMu?
Each location level has a separate field entry which is a lookup table. i.e. a controlled list of options to select from. You need to select the location levels in order from 1 to 8, as the options available at each level depends on what was previously selected. Not sure if that answered your question?

> What are the constraints on the data that can be entered?
As above - a controlled list of options to select from based on the previous location selected.

> I assume the locations must be chosen from a list, and that there's a distinct list of possible locations for each "level"?
Correct

> Do the different values in the list (e.g. Flemington) also have identifiers which could be exposed in the exported XML?
Not sure, I don't think so but not sure of the question. lets discuss on Thursday

> Is it the case that if you enter e.g. Acton at level 1, and Landmarks at level 2, does that give you a list in which Flemington would appear, whereas if you put something different at level 1 and 2 you would not get the option of Flemington in level 3? 
Correct

> Or are they independent, i.e. without any co-occurrence constraints between the different levels (i.e. the option lists for a given level are always the same regardless of what you've selected for other levels).
as above

**Comment by Conal-Tuohy** [comment]
@SimmoK can you comment on the possibility of getting persistent identifiers for the individual locations (at every level) in the EMu XML export? 

The identifier could be embedded in each record (alongside each of the existing locations' labels, as separate fields `location5_identifier` or something), or in a separate file of "locations.xml" as we did with sites.

**Comment by SimmoK** [comment]
What if i give you the EMu IRN of the Location record as a child of <LocCurrentLocationRef> tag
so a <LocCurrentLocationRef.irn> field above <LocLevel1>? But i don't know if i can do and test before next week.

![locexample](https://user-images.githubusercontent.com/36829954/44192545-2cd0ea00-a173-11e8-86c0-33651edda505.JPG)

**Comment by f27wood** [comment]
BTW there isn't a unique identifier for every local level value. The irn is for the group of locations and in affect is an identifier for the location level. 

In the example, the irn would be the unique identifier for any record with the exact same location levels. i.e. Acton - GFA - TSI - Pearling

**Comment by f27wood** [comment]
As discussed, adding some user case scenarios to assist us in resolving this.

**Task1 - Find the exhibition and module location of an object**
Display an object showing the exhibition and module location, assuming the module location is LocationLevel3

Example
Object: 231572 Horseshoe worn by Rising Fast, 1954
Location info: Acton – Landmarks – Flemington Racecourse – Case 01

**Task 2 - Find the showcase in which an object is located**
May be used in a way finding app, to take the user to the case in which the object is located.

Example one
Object: 50474 Plaque presented by the Government of NSW to commemorate the official opening of the Sydney Opera House in 1973
Location info: 
Acton - Landmarks - Bennelong Point - Case 01

Example two
Object: 233288 Example of a seat designed for the Sydney Opera House by Earl Owen
Location info: 
Acton - Landmarks - Bennelong Point - Case 02

**Task 3 - List objects in a particular gallery module**
Could be used on the modules page of Landmarks, auto linking to objects from each module
http://www.nma.gov.au/exhibitions/landmarks/about_landmarks/urban_life 
Or could be used in a way finding or tour app to identify all of the objects within a given module. 

Example
List all of the objects in the Bennelong Point module of Landmarks, noting that there are two showcases in this module. 
Location info: 
Acton - Landmarks - Bennelong Point - Case 01
Acton - Landmarks - Bennelong Point - Case 02

**Task 4 - List objects in a particular show case**
Could be used in a way finding or tour app to identify all of the objects within a given case. 

Example:
List all of the objects in the Bennelong Point module, showcase two. 
Location info: Acton - Landmarks - Bennelong Point - Case 02

**Comment by f27wood** [comment]
BTW I don;t think we are going to be able to implement this perfectly as the data levels are not consistent. However if we know the issues, we can work on improving this.

**Comment by SimmoK** [comment]
Hi @Conal-Tuohy . Can you confirm that Location IRN as in comment https://github.com/NationalMuseumAustralia/Collection-API/issues/77#issuecomment-413442356
is required? 

SImon

**Comment by Conal-Tuohy** [comment]
Hi @SimmoK -- I've talked this over with @f27wood this morning and I think I understand the point that only the most specific locations have an `irn`, now. I will need to study this issue further, and I think some additional discussion may be needed, too. To be honest at the moment I'm not sure if the location's `irn` will actually help to support the use cases [listed above](#issuecomment-414177587), though certainly it couldn't hurt to have it available. 

I'm not sure how we can support the first example use case; I don't see how we can tell which location level denotes a "module".

The second example (referring to the showcase) is easier. Is the showcase just the most specific location for a given object? Or are there locations which are the most specific but which are not "showcases"? i.e. an object being located no more specifically than as just being in a particular gallery?

The third and fourth examples (listing the objects in a location, which may or may not which have sub-locations) are easy, I think.

My concern is to model the information in a simple way that doesn't distort the underlying facts, but which doesn't necessarily capture them in their full complexity if that's not required.

**Comment by SimmoK** [comment]
Cool I'll add it.  Yes you are correct Task 1 and Task 2 aren't possible due to the variable nature of the data and structure of the locations hierarchy. Task 3 and 4 should be achievable.

**Comment by Conal-Tuohy** [comment]
@f27wood you are saying that if an API client has knowledge (independently of the API itself) of the nature of various levels of the location hierarchy (i.e. that _this one_ is a showcase, while _that one_ is a module, etc.) then they can combine that knowledge with the API to form the queries they need?

That's certainly true, though from a user's perspective it's simpler if the information they need is all in the API. One way to deal with this would be to define the entire hierarchy of locations in a separate RDF graph e.g. `locations.rdf` and make the ETL add that graph to the triple store. We already do something similar where we list "terms" (used for classifying things in the API such as "thumbnail" images). This would mean maintaining the locations independently, with identifiers and labels, and parent/child relationships, but it would allow for the API to include links from a location to "parent" and "child" locations.

**Comment by f27wood** [comment]
Yes to your first question

And yes I agree it would be preferable to have the info in the API as a locations rdf. That seems a bit tricky to do though?? So maybe out of scope for now, but something to look at for phase two.

**Comment by f27wood** [comment]
From our last conversation, I think the next step was for you Conal to think about how easy/hard it would be to create a locations.rdf. Was that right?

The main thing to note is that the locations will change at times, such as:
- When a new temporary exhibition is installed, there will be new locations
- When a temporary exhibition ends, those locations will no longer exist
- When a permanent gallery has a changeover there may be a new module so some locations will change
- When a permanent gallery is refreshed with a new gallery, locations will no longer exist and then new locations created when the new gallery is installed

Mostly, we will know about new locations as they will be part of a new exhibition development. The change overs are likely to be the ones we may miss as these are more ad hoc. However, the level 1 and level 2 locations are likely to stay the same in these instances.

**Comment by f27wood** [comment]
Tested on NMA Test and passed.

**Comment by f27wood** [comment]
tested and passed in prod.
