### ISSUE TITLE
Gallery names

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#79]
The gallery names need to be as follows:

First Australians: Gallery of Aboriginal and Torres Strait Islander Peoples
Journeys: Australia’s connections with the World gallery
Landmarks: People and Places across Australia gallery
Atrium
Old New Land: Australia’s People and Environment gallery
First Australians Focus Gallery
Open Collections
Temporary Gallery
Studio Gallery
Torres Strait Islander gallery
Xplore gallery

Simon to look into this.

Noting that they currently also have "Acton", which we do not require. I am not sure if this is changed at our end or not?

**Comment by Conal-Tuohy** [comment]
My memory was that this would be changed at your end (i.e. the gallery names would be in the EMu XML when we got it)

**Comment by f27wood** [comment]
Yes we were going to change the gallery names.. I am not sure about "Acton" though as this is location level 1... will wait and see what Simon discovers.

**Comment by f27wood** [comment]
From Simon:

I think they have made this field using LocLevel2, LocLevel1. They should be using the DisplayGallery field which should say the extended gallery name e.g.  Landmarks: People and Places across Australia gallery

**Comment by Conal-Tuohy** [comment]
OK so we should ignore the LocLevel fields now and just use DisplayGallery?

**Comment by f27wood** [comment]
Yes correct

**Comment by f27wood** [comment]
Noting the internal API will need the other locations as in:
https://github.com/NationalMuseumAustralia/Collection-API/issues/77

**Comment by Conal-Tuohy** [comment]
Done. See http://nma-dev.conaltuohy.com/object/235906

**Comment by f27wood** [comment]
Looking at this now, I don;t think using the two locations is appropriate as they are the same thing. 

In the example, 'Atrium' is the correct term for 'Main hall' and Acton has been taken from locationlevel1 and is the same for all records. 

So I would say that the public API has the location as the DisplayGallery field. And only it. In this example, "Atrium". As there is no need to include "Main hall, Acton"

The internal API then includes all of the location levels, which we have not yet decided how to map, as in issue https://github.com/NationalMuseumAustralia/Collection-API/issues/77

If that makes sense?

**Comment by f27wood** [comment]
And maybe for the simple format, instead of using location for DisplayGallery, we could use something else, as the LA format uses exhibition which is more accurate.. I will see if there is another dc term for the simplr format we can use. And then we can use location for the location levels...

**Comment by f27wood** [comment]
Another thought - it could be good to include the location as "National Museum of Australia, Canberra" ? As that is the actual place... 

I will have a think about it and we can discuss when we catch up next week, so leave as is for now.

**Comment by f27wood** [comment]
Decision made today, to only include the DisplayGallery value. And for the simple format, use a type of "Gallery"

The other locations will be included in the Internal API only and addressed as part of issue #77

**Comment by f27wood** [comment]
Moving this to 1.1, so we can use it to test the versioning, as I have needed to move issue #32 to v1.0.

**Comment by f27wood** [comment]
Tested in NMA Test and passed.

**Comment by f27wood** [comment]
tested and passed in prod.
