### ISSUE TITLE
Remove acknowledgements boolean field

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#86]
The EMu `RigCreditLine2` field is being used  in `crm:P67i_is_referred_to_by` in CRM and `acknowledgement` in simple DC.

The logic of using the boolean in `RigAcknowledgement` to ignore the `RigCreditLine2` data has been added, but there are no records using it yet, so it is not tested.  See #49

**Comment by f27wood** [comment]
test record:

229042
Canvas sulky covers

I have tested this and the acknowledgement doe snot display, which is teh expected result.

So I think this is passed, but perhaps you wish to double check Douglas?

**Comment by staplegun** [comment]
Confirmed that the `RigAcknowledgement` field will never appear in ETL processing as it is used internally within EMu to determine whether the value for `RigCreditLine2` is exported.

So code for processing the `RigAcknowledgement` should be removed to remove future confusion.

**Comment by Conal-Tuohy** [comment]
removed dead code https://github.com/NationalMuseumAustralia/Collection-API-ETL/commit/fbac47fa9fd8ec2219270f70c5d49a083c2cca55
