### ISSUE TITLE
API Key registration thank you email

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#89]
- thank you email to be reviewed and updated. Fiona to provide email template. Properties to be updated as below.
- registration emails to be CCd to api@nma.gov.au

For thank you email, please update properties as follows:

FROM: National Museum of Australia
FROM EMAIL: api@nma.gov.au
SUBJECT: Collection API key

**Comment by Conal-Tuohy** [comment]
@f27wood to test on nma-dev

**Comment by f27wood** [comment]
Tested on nma-dev and email format AOK thx, however email settings not yet changed:

FROM: National Museum of Australia
FROM EMAIL: api@nma.gov.au
SUBJECT: Collection API key for <name>

Note - I like how you have included the name in the subject, so added this here.

**Comment by f27wood** [comment]
Also please CC emails to api@nma.gov.au so we can see who is registering
