### ISSUE TITLE
Embed API Explorer in NMA website

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#92]
Provide code to embed into NMA website, possibly as an iframe (preferably not as a query would not be bookmarked).

As a backup, apply website design template for hosting on the API server.

**Comment by staplegun** [comment]
Initial implementation at http://www.nma.gov.au/collections/our-apis/api-explorer

The Squiz Matrix CMS content box accepts javascript elements when the properties are set to `Raw HTML`.

HTML 5.2 allows `<style>` element inside the `<body>`, however some older browsers may not support this.

Unfortunately the production API does not support CORS so in the meantime the explorer is pointing to `nma-dev.conaltuohy.com`

**Comment by f27wood** [comment]
It is full width now, which works much better.

**Comment by f27wood** [comment]
CORS issue fixed and all working in NMA Prod, so closing this.
