### ISSUE TITLE
Narrative for internal API only

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#98]
I created a new narrative in EMu a while ago:

3373
NMA website - homepage set

However I cannot retrieve this using an API key, as follows:

https://data.nma.gov.au/narrative/3373?apikey=swIxipP4bWPvL0PTMyP8e7Igtv1ArOfk

I'm not sure if the issue is with the API code or the xml not including it, or something I have done/not done in EMu.

I have set the Intended Audience as "Internal API only", thinking this would mean it is included in the XML but only shown in the internal API.

This is a high priority as we need this to work for our website integration.

**Comment by SimmoK** [comment]
I'll chekc this out, could be an export issue

**Comment by Conal-Tuohy** [comment]
At the moment there's no support for "internal API only" narratives. Setting the "intended audience" field to anything other than "Collection Explorer publish" will suppress the narrative altogether. 

Can I ask what's the need to hide this narrative from the public API?

**Comment by Conal-Tuohy** [comment]
Looking at the filtering code again I realise it will allow _all_ narratives to flow into the internal dataset; only the public dataset is filtered. So I think @SimmoK's fix should do it.

**Comment by f27wood** [comment]
Oh goodo! And yes have tested with a draft one and it is in the internal API 
https://data.nma.gov.au/narrative/3365?apikey=swIxipP4bWPvL0PTMyP8e7Igtv1ArOfk

**Comment by f27wood** [comment]
Fixed!
