### ISSUE TITLE
Images with blank CC status to be included in Internal API

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#99]
We have been testing the API integration with our website. One function is that we can embed an object that shows an image.

Testing this with object 70146, however no image came across.

I believe this is because the Creative Commons status is blank. i.e. it has no value entered.

When the Creative Commons status is blank, we would like the image included in the internal API. 

Is that possible?

**Comment by Conal-Tuohy** [comment]
I believe the desired behaviour is now actually in effect (with the various changes to the image redaction code I finished yesterday) for any updated records, and will roll out to all records on the weekend when Solr's data is updated in full.

**Comment by Conal-Tuohy** [comment]
http://data/nma.gov.au/object/70146# is still missing images in the internal API

**Comment by Conal-Tuohy** [comment]
http://csapi-test.nma.gov.au/object/70146# (portrait of Phar Lap) now shows images to "internal" users and hides images from "public" users. Rolling out to http://data.nma.gov.au/object/70146# tonight

**Comment by f27wood** [comment]
Closed noting new issue 
https://github.com/NationalMuseumAustralia/Collection-API/issues/105
